import { Inter } from 'next/font/google'
import './globals.css'
import LoginBoundary from '@/components/layouts/LoginBoundary'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create.xyz App',
  description: 'Generated by create.xyz',
}

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginBoundary>
          {children}
        </LoginBoundary>
      </body>
    </html>
  )
}